#!/usr/bin/env bash -euE

# go to the root of the solution
cd "$(dirname "${0}")"

# configurations
_SLN='Rot.Game.sln'
_CONTENT_ROOT='Rot.Game'
_PATH_OUTPUT='Rot.Data/T4/ContentPath.cs'

_help() {
    cat <<FIN
it is the main interface of script utilities (macOS only)

content  build content
build    build content & source
run      just run the compiled application
all      build and then run
path     just print the content paths
FIN
}

_content() {
  cd "${_CONTENT_ROOT}"
  msbuild /t:BuildContent
  cd ../
  ./pathgen > "${_PATH_OUTPUT}"
}

_build() {
  msbuild "${_SLN}" "/p:configuration=Debug" "/p:platform=Any CPU" "/t:build"
}

_run() {
  env "DYLD_LIBRARY_PATH=$(pwd)/${_CONTENT_ROOT}/bin/Debug/osx/" mono "$(pwd)/${_CONTENT_ROOT}/bin/Debug/${_CONTENT_ROOT}.exe"
}

[ $# -eq 0 ] && _help && exit 0

_cmd="${1}"
shift 1

_main() {
    case "${_cmd}" in
        'b' | 'build')
            _content "$@" &
            _build "$@" ;;
        'c' | 'content')
            _content "$@" ;;
        'r' | 'run')
            _run "$@" ;;
        'a' | 'all')
            _content "$@" &
            _build "$@"
            _run "$@" ;;
        'p' | 'path')
            ./scripts/pathgen ;;
        'h' | 'help')
            _help ;;
        *)
            echo 'no matching command' ;;
    esac
}

_main "$@"
