#!/usr/bin/env bash -euE
# exports constants and some utilitieies

# the only absolute path in use
_ROOT="$(cd "$(dirname "$(dirname "$0")")" && pwd)"

# paths relative to the root
_SLN='Rot.Game.sln'
_CONTENT_PROJ='Rot.Game'
_CONTENT_DEST='Rot.Data/ContentPath.cs'
_EXEC_PROJ='Rot.Game'

_RUN() {
    local _BASE="${_ROOT}/scripts"
    _cmd="$1"
    shift 1
    if [ ! -x "${_BASE}/${_cmd}" ] ; then
        echo "could not find executable script: \`${_cmd}\`" 1>&2
        return 1
    else
        "${_BASE}/${_cmd}" "$@"
    fi
}

_REQUIRE() {
    _any_err=0
    while true ; do
        [ $# -eq 0 ] && break
        if ! command -v "$1" 1>/dev/null 2>&1 ; then
            echo "error: required command \`$1\` doesn't exist" 1>&2
            _any_err=1
        fi
        shift 1
    done
    return $_any_err
}
