#!/bin/bash -euE
# generates "${_ROOT}/${_CONTENT_PATH}"

IFS=$'\n\t'
source "$(dirname "$0")/_configure"

_NAME_SPACE=Nez

cd "${_ROOT}/${_CONTENT_PROJ}"

_print_indent() {
    for __ in $(seq ${1}) ; do
        printf '    '
    done
}

_standarize() {
    printf "${1}" | sed 's/^static/@Static/g' | gsed 's/.*/\u&/' | sed 's/\..*$//g'
    # TODO: enable other names that are hidden by keywords
}

_rec_dir() {
    local _next_dir="${1}"
    cd "${_next_dir}"
    local _indent="${2}"
    local _basepath="${3}"

    _print_indent "${_indent}"
    printf '%s\n' "public static class ${_next_dir} {"
    _indent=$(($_indent+1))

    # print files
    for __file in $(fd -t f -d 1) ; do
        local _name="$(_standarize "${__file}")"
        _print_indent "${_indent}"
        printf '%s\n' "public static readonly string ${_name} = \"${_basepath}/${__file}\";"
    done

    # recursively print directories
    for __dir in $(fd -t d -d 1) ; do
        _rec_dir "${__dir}" "$(($_indent))" "${_basepath}/${__dir}"
    done

    printf '%s\n' "$(_print_indent "$((${_indent}-1))")}"
    cd ../
}

printf '%s\n' "namespace ${_NAME_SPACE} {"
_rec_dir Content 1 Content
printf '%s\n' '}'
