= Architecture

GUI games are much harder to make compared to CLI ones. This is because we can't `sleep` while visualizing the game. Stop & resume is the most difficult part of the system, I guess.

I havn't found a complete solution, but my game is working under the following ideas.

== Engine - View separation

We split the game into *Engine* and *UI*. Engine is the internal game state, UI is the other (input and view).

The core of the `Engine` is the `RlGameState`. When we `tick` it, it returns `RlGameProgress`, with which UI can pull enough context to visualize what happened.

NOTE: The terminology (engine/UI) is based on https://journal.stuffwithstuff.com/2014/07/15/a-turn-based-game-loop/[this blog post], but they don't directly apply to our project names; `Rot.Engine` is almost same as the internal game state, but `Rot.Ui` is a view/input component for the `Rot.Game` application, and they are the UI to the Engine.

== Engine = processor of contents

We develop the game by adding contents to the engine.

=== Mutation via events

We mutate the game by pushing `RlEvent` to the engine. `RlEvent` is not only primitive events, such as `GiveDamage`, but also **actions** of entities. This is natural because action events are a kind of mutation; they result in some primitive events, e.g. `MeleeAttack` → `Hit` → `GiveDamage`.

Then how the events handled?

=== Layers of logics (https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern[Chain of Responsibility] pattern)

When we add a new feature to the game, we may want to add some logic to existing `RlEvent` handlings. For example, let's add "dissy" state. If an entity is "dissy", they may walk in a random direction. How shall we add that logic to the `Walk` event handling?

Since we add more *extensions* to the engine later, we don't want to write an action handling logic at *one place*. Instead, we collect each logic via `RlEventHub`, which dispatches *event handlers* depending on their `precedence`. This is a variant of the https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern[Chain of Responsibility] pattern.

Logics are combined as `RlRule` s. Each `RlRule` can insert some logic to any `RlEvent`.

== Visualizing `RlEvent` s

This is in progress. I have to dig in and find more details.

